### ISSUE TITLE
freeswitch.environment.EC2 contains true, which is an invalid type

### ISSUE THREAD

**Issue by hthetiot** [flaccid/docker-freeswitch#1]
> docker-compose -f docker-compose.yml -f docker.compose.ec2.yml up -d

Is causing:
> ERROR: The Compose file './docker.compose.ec2.yml' is invalid because:
freeswitch.environment.EC2 contains true, which is an invalid type, it should be a string, number, or a null

**Comment by flaccid** [comment]
Thanks, fixed!
