### ISSUE TITLE
Unsupported config option for services.freeswitch: 'net'

### ISSUE THREAD

**Issue by hthetiot** [flaccid/docker-freeswitch#2]
ERROR: The Compose file './docker-compose.yml' is invalid because:
Unsupported config option for services.freeswitch: 'net'

Use network_mode instead:
> network_mode: host

Ref:
- https://docs.docker.com/compose/compose-file/#network_mode

**Comment by flaccid** [comment]
It is actually valid in compose v1. I have bumped to compose v2.
